# Generated by Django 4.2.5 on 2024-02-19 03:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role_user',
            name='id_role',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='users.role'),
        ),
        migrations.AlterField(
            model_name='role_user',
            name='id_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
