# Generated by Django 4.2.5 on 2024-02-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_staff_user_is_superuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role_user',
            old_name='id_role',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='role_user',
            old_name='id_user',
            new_name='user',
        ),
    ]
