# Generated by Django 4.2.5 on 2024-02-26 03:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('rank', models.IntegerField()),
                ('type_of_ownership', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='companies.company')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'service_company',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='Specialization_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.specialization')),
            ],
            options={
                'db_table': 'specialization_company',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('companies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.service_company')),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Order_User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.order')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'order_user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='companies.service'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=150)),
                ('companies', models.ManyToManyField(to='companies.company')),
            ],
            options={
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='Day_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('day_of_start_week', models.DateField()),
                ('weekday', models.IntegerField()),
                ('companies', models.ManyToManyField(to='companies.company')),
            ],
            options={
                'db_table': 'day_of_work',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='phones',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.phone'),
        ),
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.ManyToManyField(to='companies.service'),
        ),
        migrations.AddField(
            model_name='company',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.specialization'),
        ),
        migrations.AddField(
            model_name='company',
            name='specializations',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.specialization_company'),
        ),
    ]
