# Generated by Django 4.2.5 on 2024-03-03 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('day_of_start_week', models.DateField()),
                ('weekday', models.IntegerField()),
            ],
            options={
                'db_table': 'day_of_work',
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'holiday',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.service')),
            ],
            options={
                'db_table': 'specialization',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField()),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='companies.service')),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('rank', models.IntegerField(null=True)),
                ('type_of_ownership', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=50)),
                ('day_of_work', models.ManyToManyField(to='companies.day_of_work')),
                ('holidays', models.ManyToManyField(to='companies.holiday')),
                ('orders', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.order')),
                ('phones', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.phone')),
                ('services', models.ManyToManyField(to='companies.service')),
                ('specializations', models.ManyToManyField(to='companies.specialization')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
