# Generated by Django 4.2.5 on 2024-02-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('comment', models.CharField(max_length=150)),
                ('companies', models.ManyToManyField(to='companies.company')),
            ],
            options={
                'db_table': 'holidays',
            },
        ),
    ]
