# Generated by Django 4.2.5 on 2024-03-02 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_alter_company_address_alter_company_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='orders',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.order'),
        ),
    ]
