# Generated by Django 4.2.5 on 2024-02-24 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_company', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
                ('id_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.service')),
            ],
            options={
                'db_table': 'service_company',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
            ],
            options={
                'db_table': 'phone',
            },
        ),
        migrations.CreateModel(
            name='Day_of_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_open', models.TimeField()),
                ('time_close', models.TimeField()),
                ('day_of_start_week', models.DateField()),
                ('weekday', models.IntegerField()),
                ('companies', models.ManyToManyField(to='companies.company')),
            ],
            options={
                'db_table': 'day_of_work',
            },
        ),
    ]
