# Generated by Django 4.2.5 on 2024-03-02 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_company_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='login',
        ),
    ]
