# Generated by Django 4.2.5 on 2024-02-24 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_specialization_remove_phone_company_company_phones_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='id_specialization',
            new_name='specialization',
        ),
        migrations.RenameField(
            model_name='order_user',
            old_name='id_order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='order_user',
            old_name='id_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='service_company',
            old_name='id_company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='service_company',
            old_name='id_service',
            new_name='service',
        ),
    ]
