# Generated by Django 4.2.5 on 2024-02-24 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_rename_id_specialization_company_specialization_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
        migrations.AlterModelTable(
            name='holiday',
            table='holiday',
        ),
    ]
