# Generated by Django 4.2.5 on 2024-02-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_company_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='city',
        ),
    ]
